### ISSUE TITLE
client_lib/ABI_VERSION: No such file or directory

### ISSUE THREAD

**Issue by Catchher** [p4lang/p4app-switchML#12]
when I exec  _make DPDK=1_ in path **dev_root**, it shows
 _cat: /p4app-switchML/dev_root/client_lib/ABI_VERSION: No such file or directory_ ,
Does it matter if this prompt is left alone?

**Comment by Catchher** [comment]
and after I exec _python setup.py install_ in path **pytorch_plugin**, it seems installed successfully,
but when I test torch_switchml, it shows
_>>> import torch
>>> import torch_switchml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /root/anaconda3/lib/python3.9/site-packages/torch_switchml-0.1-py3.9-linux-x86_64.egg/torch_switchml.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTIN6google8protobuf7MessageE_

when I 
**export LD_PRELOAD=/root/anaconda3/lib/libprotoc.so.30.0.1:/root/anaconda3/lib/libprotobuf.so.30.0.1**
the error changed into
_>>> import torch
>>> import torch_switchml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /root/anaconda3/lib/python3.9/site-packages/torch_switchml-0.1-py3.9-linux-x86_64.egg/torch_switchml.cpython-39-x86_64-linux-gnu.so: undefined symbol: rte_mempool_ops_table_

I have no clue about this, can you give me some advice

**Comment by OasisArtisan** [comment]
Hey, thanks for reaching out.
When you run python setup.py you have to pass the same build variables that you used in order to link the needed libraries.
So you should run 
`DPDK=1 python setup.py`

I would also like to point out that the PyTorch plugin has not yet been tested for performance so use at your own discretion and if you find any issues we would be happy to hear from you about them.

**Comment by Catchher** [comment]
I'm sorry I didn't explain the details clearly, because I've already run the command 
`DPDK=1 python setup.py`
I have tested many times according to the document, and there are always such errors, and I have tried many methods, which can not solve the problem. 

So I turned to **pytorch_patch** method, which can successfully `import torch`, but when I run the training code, it reports such an error
```
EAL:   probe driver: 8086:1581 net_i40e
E0705 02:03:15.409107 32277 dpdk_master_thread_utils.inc:277] Flow isolated mode failed: 1 Function not implemented
i40e_flow_set_fdir_inset(): Invalid input set
F0705 02:03:16.098023 32277 dpdk_master_thread_utils.inc:154] Flow rule can't be added: 13Invalid pattern mask.
*** Check failure stack trace: ***
    @     0x7fec058b20cd  google::LogMessage::Fail()
    @     0x7fec058b3f33  google::LogMessage::SendToLog()
    @     0x7fec058b1c28  google::LogMessage::Flush() 
```

The following functions report errors
```
+i40e_flow_set_fdir_inset(struct i40e_pf *pf,
+			 enum i40e_filter_pctype pctype,
+			 uint64_t input_set)
+{
+	struct i40e_hw *hw = I40E_PF_TO_HW(pf);
+	uint64_t inset_reg = 0;
+	uint32_t mask_reg[I40E_INSET_MASK_NUM_REG] = {0};
+	int i, num;
+
+	/* Check if the input set is valid */
+	if (i40e_validate_input_set(pctype, RTE_ETH_FILTER_FDIR,
+				    input_set) != 0) {
+		PMD_DRV_LOG(ERR, "Invalid input set");
+		return -EINVAL;
+	}
+  
```

The following is the dpdk network card we use

```
3b:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE backplane (rev 02)
3b:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE backplane (rev 02)
3b:00.2 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE backplane (rev 02)
3b:00.3 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 02)  
```

I have tried many methods, but they are useless. T _ T

**Comment by OasisArtisan** [comment]
I will investigate the pytorch_plugin issue when compiling with DPDK and get back to you.

As for the pytorch_patch, you seem to have it installed correctly. The error you are getting doesn't seem to be an integration issue but rather a NIC compatibility issue. Can you run the helloworld example and confirm that you will get the same errors?

**Comment by Catchher** [comment]
THANKS.
I can run the `helloword` with **switchml.cfg**, which was generated automatically with no modification.
```
(patch) root@work2:/home/test/p4app-switchML/dev_root/build/bin# ls
hello_world  switchml.cfg
(patch) root@work2:/home/test/p4app-switchML/dev_root/build/bin# ./hello_world
Hello world!. Starting the switchml context
Allocating data
Initializing data
Submitting all reduce jobs
Waiting for all jobs to finish
Stopping the switchml context
Verifying results
Data verified successfully exiting main program
```
But, with the **switchml.cfg** modified, it reproduce the same error as above.
```
(patch) root@work2:/home/test/p4app-switchML/dev_root/build/bin# ls
hello_world  switchml.cfg  switchml.cfg.old
(patch) root@work2:/home/test/p4app-switchML/dev_root/build/bin# ./hello_world
Hello world!. Starting the switchml context
Allocating data
Initializing data
Submitting all reduce jobs
Waiting for all jobs to finish
EAL: Detected 48 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:3b:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1581 net_i40e
E0707 03:05:06.800369 11495 dpdk_master_thread_utils.inc:277] Flow isolated mode failed: 1 Function not implemented
i40e_flow_set_fdir_inset(): Invalid input set
F0707 03:05:07.192461 11495 dpdk_master_thread_utils.inc:154] Flow rule can't be added: 13Invalid pattern mask.
*** Check failure stack trace: ***
    @     0x7f1cf02a40cd  google::LogMessage::Fail()
    @     0x7f1cf02a5f33  google::LogMessage::SendToLog()
    @     0x7f1cf02a3c28  google::LogMessage::Flush()
    @     0x7f1cf02a6999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55c4be4786d9  switchml::InsertFlowRule()
    @     0x55c4be4793a5  switchml::InitPort()
    @     0x55c4be47a371  switchml::DpdkMasterThread::operator()()
    @     0x7f1ceffcc6df  (unknown)
    @     0x7f1cefa766db  start_thread
    @     0x7f1cee67a61f  clone
Aborted (core dumped)

```
Following is the general info of **switchml.cfg**, running on machine, work2.
```
[general]
    rank = 1
    num_workers = 2
    num_worker_threads = 4
    max_outstanding_packets = 256
    packet_numel = 256
    backend = dpdk
    scheduler = fifo
    prepostprocessor = cpu_exponent_quantizer
    instant_job_completion = 0
    controller_ip_str = 10.99.70.49
    controller_port = 50099
    timeout = 10
    timeout_threshold = 100
    timeout_threshold_increment = 100
    --(derived)--
    max_outstanding_packets_per_worker_thread = 64
I0707 03:05:06.616739 11491 config.cc:249]
[backend.dpdk]
    worker_port = 4000
    worker_ip = 2.2.2.4
    cores = 8-11
    extra_eal_options = -w 0000:3b:00.1
    port_id = 0
    pool_size = 131072
    pool_cache_size = 512
    burst_rx = 64
    burst_tx = 64
    bulk_drain_tx_us = 0
```
BTW, the `switchml.cfg` of work1 is different from work2 only on worker_ip, whitch is 2.2.2.3.

**Comment by lvleiai123** [comment]
here are my nic info:
```
Device #1:
----------
  Device Type:      ConnectX4
  Part Number:      MCX415A-CCA_Ax
  Description:      ConnectX-4 EN network interface card; 100GbE single-port QSFP28; PCIe3.0 x16; ROHS R6
  PSID:             MT_2140110033
  PCI Device Name:  d8:00.0
  Base GUID:        506b4b03000fb5c4
  Base MAC:         506b4b0fb5c4
  Versions:         Current        Available
     FW             12.28.2006     12.28.2006
     PXE            3.6.0102       3.6.0102
     UEFI           14.21.0017     14.21.0017
  Status:           Up to date
```

When i use it for switchml train， got errors like this：

```
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x100a94000 != 0x7fe4d3e00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x1016f5000 != 0x7fe0d3c00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x102356000 != 0x7fdcd3a00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x102fb7000 != 0x7fd8d3800000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x103c18000 != 0x7fd4d3600000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x104879000 != 0x7fd0d3400000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x1054da000 != 0x7fccd3200000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x10613b000 != 0x7fc8d3000000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
F0707 03:14:46.742125 28820 dpdk_master_thread_utils.inc:190] No Ethernet ports
*** Check failure stack trace: ***
    @     0x7fe93c7d40cd  google::LogMessage::Fail()
    @     0x7fe93c7d5f33  google::LogMessage::SendToLog()
    @     0x7fe93c7d3c28  google::LogMessage::Flush()
    @     0x7fe93c7d6999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe94ebd8f01  switchml::InitPort()
    @     0x7fe94ebda811  switchml::DpdkMasterThread::operator()()
    @     0x7fe95b65dbf4  execute_native_thread_routine
    @     0x7fe974ce36db  start_thread
    @     0x7fe974a0c61f  clone
```

switchml cann't find Ethernet ports ，if it has requirements for network card type ？what can i do for this problem.

**Comment by mcanini** [comment]
Can you please check whether the DPDK mlx4 driver was built?
I fear that by default it is not built.

**Comment by AmedeoSapio** [comment]
Hi,
are you trying to use the X710 NIC? If this is the case, I think you don't need the Mellanox driver, but the I40e driver. 
This problem is probably related to the Flow Director support in that I40e driver. 
We use this feature to install flow rules in the NIC to distribute packets to the different threads. Every thread receives packets with a different UDP destination port. The flow rule matches the destination port and sends the packet to the right queue associated with one thread.
You can try to comment the function [InsertFlowRule](https://github.com/p4lang/p4app-switchML/blob/1fc7e676919a51c6f67bcf823b72e1d52769c6a4/dev_root/client_lib/src/backends/dpdk/dpdk_master_thread_utils.inc#L105) that is inserting the flow rule, and test with a single thread with `num_worker_threads = 1`. This should work as the flow rule is not needed in this case. 

But to reach high performance you need more than one thread, and we would need to understand why that flow rule insertion does not work with your NIC. Can you try to add that flow rule using testpmd?

**Comment by Catchher** [comment]
THANKS.
I have tried your suggestion and run `helloworld` again.
It shows such an error:
![error](https://user-images.githubusercontent.com/26021997/178099138-a9a7a8f8-6629-49f6-a169-12487c44c39e.PNG)
Following is my `switchml.cfg` info,
![cfg](https://user-images.githubusercontent.com/26021997/178099173-1cdecbfa-8fe6-4754-9602-f5ee7cbc8295.PNG)
NIC info.
![3b001](https://user-images.githubusercontent.com/26021997/178099221-7cda3191-a27b-4648-ab21-5a6e41c02f3f.PNG)
I comment the function `InsertFlowRule`, it can be see in
[dpdk_master_thread_utils.txt](https://github.com/p4lang/p4app-switchML/files/9076162/dpdk_master_thread_utils.txt)
BTW, I have set **hugepages** as following picture shows to solve the **EAL init problem** which can be see in the last image:
![1024](https://user-images.githubusercontent.com/26021997/178099393-f970c7e6-d372-47d9-9755-f164c4917995.PNG)
![EAL](https://user-images.githubusercontent.com/26021997/178099416-4aa39927-0ab8-4a78-b1b0-871abc4a3c80.PNG)

**Comment by AmedeoSapio** [comment]
Hi, 
I believe the Intel X710 NIC needs to be bound to the `igb_uio` driver to work with DPDK. Yours is currently bound to the kernel driver `i40e`, which is why DPDK does not see it. You probably need to remove the IP address from the interface (so that it is no longer "active") and then use the [dpdk-devbind tool](https://doc.dpdk.org/guides/tools/devbind.html) to bind it to `igb_uio`.

For the hugepages, it would be better to set 1GB hugepages (keep this in mind in case you get a `Cannot allocate memory [12]` error). 
A small correction to my previous statement, it may be that one thread is good enough for you since you are only using 10Gbps (we have used up to 8 threads to reach 100Gbps). But it depends on your system clock speed, memory bandwidth, etc.

**Comment by Catchher** [comment]
Hi,
I have run the command` ifconfig ens7f1 down` and used the [dpdk-devbind tool](https://doc.dpdk.org/guides/tools/devbind.html) to bind `ens7f1` to `igb_uio`.
![newNIC](https://user-images.githubusercontent.com/26021997/178182172-11d87ff5-837c-4149-a896-4dcf6ab7ba16.PNG)

It seems I have solve the problem
```
i40e_flow_set_fdir_inset(): Invalid input set
F0707 03:05:07.192461 11495 dpdk_master_thread_utils.inc:154] Flow rule can't be added: 13Invalid pattern mask.
```
and following is the result I got.
![dpdk](https://user-images.githubusercontent.com/26021997/178181900-0195d243-b281-4cb9-b70d-dddb651b3743.PNG)
I waited for a long time, but the program didn't continue. and the following problem remains：
`E0707 03:05:06.800369 11495 dpdk_master_thread_utils.inc:277] Flow isolated mode failed: 1 Function not implemented`

**Comment by AmedeoSapio** [comment]
Hi, 
the `Flow isolated mode` error is not an issue, as it is only an optimization to simplify the job of the DPDK driver (see [here](https://doc.dpdk.org/guides/prog_guide/rte_flow.html#flow-isolated-mode) for the isolated mode description). Evidently the driver for your NIC is not implementing it, but the program should work even if that error is showed. 

Are you running with the InsertFlowRule function commented out? Is it running with a single worker thread?
It is difficult for me to understand what is going on as I don't have the same NIC to reproduce this, so any information you can provide is helpful. 
Can you compile with the `DEBUG=1` flag so that we get more log messages? If you still see the SegFault, can you run with gdb and print the stack trace?

**Comment by Catchher** [comment]
Hi,
I comment the [InsertFlowRule](https://github.com/p4lang/p4app-switchML/blob/1fc7e676919a51c6f67bcf823b72e1d52769c6a4/dev_root/client_lib/src/backends/dpdk/dpdk_master_thread_utils.inc#L105) function, it can be see in this file 
[dpdk_master_thread_utils.txt](https://github.com/p4lang/p4app-switchML/files/9090581/dpdk_master_thread_utils.txt)
, and run make DPDK=1 in third_party directory, then run  make DPDK=1 DEBUG=1 in client_lib directory, at last, run  make helloworld DPDK=1 DEBUG=1 in  examples directory.
As for switchml.cfg, I set `num_worker_threads = 1` and `cores = 8`.
I find an unreasonable place which can be see in the following image, it seems there is a number divided by 0.
![debug](https://user-images.githubusercontent.com/26021997/178430533-2de3881f-8557-4f8f-aa78-248dede1acd8.PNG)
