### ISSUE TITLE
ERROR - '$PKTGEN_PORT_CFG'

### ISSUE THREAD

**Issue by 1908639561** [p4lang/p4app-switchML#13]
Hi，
I'm trying to benchmark SwitchML on a Tofino switch (Wedge100BF-32X-O-AC-F), but I'm having some difficulty running the controller. I think I have successfully compiled the P4 program and deployed it on the switch. When I run the controller under "/dev_root/controller" on the switch, it gives me the following error.
![1656927166290](https://user-images.githubusercontent.com/95405577/177126968-75ead45d-51d6-41a6-8ecd-a78ed67a86d3.png)
Controller Log:
![1656927116049](https://user-images.githubusercontent.com/95405577/177126788-b1759797-140f-412a-9b1d-5ad1c8eaf1de.png)
Environment:

- Tofino Switch: Wedge100BF-32X-O-AC-F
- SDE: 9.8.0
- Python:3.6.9

Thank you.

**Comment by AmedeoSapio** [comment]
Hi, 
the code was tested with SDE 9.6.0, but since SDE 9.7 the name of the pktgen table has changed. 
I have now updated the controller to support SDE 9.7+ in 1fc7e676919a51c6f67bcf823b72e1d52769c6a4
