### ISSUE TITLE
No Ethernet ports

### ISSUE THREAD

**Issue by lvleiai123** [p4lang/p4app-switchML#16]
here are my nic info:

Device #1:
----------
  Device Type:      ConnectX4
  Part Number:      MCX415A-CCA_Ax
  Description:      ConnectX-4 EN network interface card; 100GbE single-port QSFP28; PCIe3.0 x16; ROHS R6
  PSID:             MT_2140110033
  PCI Device Name:  d8:00.0
  Base GUID:        506b4b03000fb5c4
  Base MAC:         506b4b0fb5c4
  Versions:         Current        Available
     FW             12.28.2006     12.28.2006
     PXE            3.6.0102       3.6.0102
     UEFI           14.21.0017     14.21.0017
  Status:           Up to date
When i use it for switchml train， got errors like this：

EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: WARNING! Base virtual address hint (0x100a94000 != 0x7fe4d3e00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x1016f5000 != 0x7fe0d3c00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x102356000 != 0x7fdcd3a00000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x102fb7000 != 0x7fd8d3800000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x103c18000 != 0x7fd4d3600000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x104879000 != 0x7fd0d3400000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x1054da000 != 0x7fccd3200000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x10613b000 != 0x7fc8d3000000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
F0707 03:14:46.742125 28820 dpdk_master_thread_utils.inc:190] No Ethernet ports
*** Check failure stack trace: ***
    @     0x7fe93c7d40cd  google::LogMessage::Fail()
    @     0x7fe93c7d5f33  google::LogMessage::SendToLog()
    @     0x7fe93c7d3c28  google::LogMessage::Flush()
    @     0x7fe93c7d6999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe94ebd8f01  switchml::InitPort()
    @     0x7fe94ebda811  switchml::DpdkMasterThread::operator()()
    @     0x7fe95b65dbf4  execute_native_thread_routine
    @     0x7fe974ce36db  start_thread
    @     0x7fe974a0c61f  clone
switchml cann't find Ethernet ports ，if it has requirements for network card type ？what can i do for this .

when i run switchml program，should i put nic into dpdk status manually ?

(base) root@work4:/p4app-switchML/dev_root/third_party/dpdk/usertools# ./dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:86:00.0 'Ethernet Controller X710 for 10GbE backplane 1581' drv=igb_uio unused=i40e
0000:d8:00.0 'MT27700 Family [ConnectX-4] 1013' drv=igb_uio unused=mlx5_core

**Comment by AmedeoSapio** [comment]
Hi,
if you want to use the ConnectX 4 NIC with DPDK, there is no need to bind the NIC to the igb_uio driver, as the Mellanox driver (mlx5_core) is already compatible. 

You should bind the NIC back to the mlx5_core driver, and make sure that the `extra_eal_options` value in the configuration file has the correct PCIe identifier of your NIC, in your case:
`extra_eal_options = -w 0000:d8:00.0`
Let us know if this solves the issue.

**Comment by lvleiai123** [comment]
thanks， i have solved this problem successfully。
i have already changed my network card and i'm using MLX5 now，just add arguement "MLX5=1" when i run "make"
![Snipaste_2022-07-13_14-42-46](https://user-images.githubusercontent.com/59639597/178668056-1c9256ac-8f9a-4a1a-82c8-9a8f03081fa5.png)
