### ISSUE TITLE
The acceleration effect does not meet the requirements。

### ISSUE THREAD

**Issue by lvleiai123** [p4lang/p4app-switchML#18]
i can run switchml completely。however ,i can not get the ideal results。
i got 8785 seconds without switchml and got 9067 seconds with p4app-switchml ，why it have not acceleration effect at all ,  what can i do to adjust parameter。
use switchml
![base_r1](https://user-images.githubusercontent.com/59639597/180907030-ec42128d-1bf2-4f77-b29e-a25c9edbb4c1.png)
without switchml
![py17_r1](https://user-images.githubusercontent.com/59639597/180907083-fa431ae5-39bb-4cdb-bc36-8ea8173ace88.png)

switchml.cfg
![Snipaste_2022-07-26_10-08-33](https://user-images.githubusercontent.com/59639597/180907259-ce829fe5-826b-41e4-9aee-8dbebd6e637e.png)

which parameter should i try ?

**Comment by OasisArtisan** [comment]
I assume you are using PyTorch. Which integration method are you using?. 

I would increase the num_worker threads until it no longer provides benefits. 1 is too small. Try 4, 8 and other values and see how that affects performance.

The number of outstanding packets is another important option. Try 128, 256, 512 and see which works best.

If playing with both these doesn't improve your performance let me know we can take a look at other configurations.
Of course you can expect even better performance with the RDMA backend if your setup supports it.

**Comment by lvleiai123** [comment]
i have changed the  num_worker_threads  and  max_outstanding_packets, however，it dose not work at all :( 
So， i give up DPDK and i'm using RDMA now。
i can run helloworld with RDMA successfully。
![Snipaste_2022-07-29_10-27-31](https://user-images.githubusercontent.com/59639597/181670301-6b465533-5fa9-460c-b936-b15e5f146d2e.png)

however ,i can not run pytorch。 And also  lots of ‘Retransmitted’ packets in Controller
![Snipaste_2022-07-29_10-34-08](https://user-images.githubusercontent.com/59639597/181670894-1f250c6e-2146-4c2f-a5eb-00ac2e512e47.png)
i have captured the packets by command "tcpdump -i ens17f1" and don' understand  why Data are “0”
![Snipaste_2022-07-29_10-40-30](https://user-images.githubusercontent.com/59639597/181671567-fdb2b437-1ddf-4dee-999c-3477df15f5e0.png)

here are logs ，helloworld （success） and  pytorch  (faild )，“fifo_scheduler.cc:46] Queued job id” is only difference。
![Snipaste_2022-07-29_10-43-10](https://user-images.githubusercontent.com/59639597/181671878-65899bfe-c40b-4374-9733-7bf31f45a4d1.png)
helloworld
[helloworld.txt](https://github.com/p4lang/p4app-switchML/files/9215657/helloworld.txt)
pytorch
[pytorch.txt](https://github.com/p4lang/p4app-switchML/files/9215662/pytorch.txt)

**Comment by OasisArtisan** [comment]
Okay let us start from the beginning,
How did you setup SwitchML ? How are you running the controller, the p4 code, and the client library?

Start debugging without PyTorch. Once you are sure that everything is working you can run through PyTorch. 
You said that the helloworld example is working? Does it work for any configuration? Have you tried running with the benchmark as well? There is a verify option in the benchmark that checks if you are receiving correct messages.

**Comment by lvleiai123** [comment]
i  used './run_switchd.sh -p switchml' in barefoot switch, and it works

```
bfruntime gRPC server started on 0.0.0.0:50052

        ********************************************
        *      WARNING: Authorised Access Only     *
        ********************************************
bfshell>
```

Also，controller is in barefoot switch ，and i run it with command  'root@sonic:/sde/p4app-switchML/dev_root/controller# python switchml.py --program switchml --switch-mac 00:11:22:33:44:55 --switch-ip 2.2.2.100' 

```
SwitchML>show_ports
  Port Up Valid Enabled Speed  FEC    Tx Packets        Tx Bytes        Rx Packets        Rx Bytes        Rx Errors        Tx Errors        FCS Errors
  5/0  1    1      1    100G  REED_SOLOMON        6               564               3               262               0                0                0
  7/0  1    1      1    100G  REED_SOLOMON        5               450               2               188               0                0                0
  9/0  1    1      1    100G  REED_SOLOMON        3               262               2               188               0                0                0
  11/0 1    1      1    100G  REED_SOLOMON        2               168               2               188               0                0                0

```
client lib ：i make it with command  " make RDMA=1  DEBUG=1  VCL=0  " in client_lib/  foldder 

Follow your suggest, i test  benchmark  and  got successful 
```
(base) root@work1:~/p4app-switchML/dev_root/build/bin# ./allreduce_benchmark
Signal handler thread started. Waiting for any signals.
Submitting 5 warmup jobs.
Warmup finished.
Submitting 10 jobs.
Job(s) #0# finished. Duration: #2049582575# ns Goodput: #4.19107# Gbps.
Job(s) #1# finished. Duration: #2090310713# ns Goodput: #4.10941# Gbps.
^CSignal 2 received, preparing to exit...
Signal handler thread is exiting
(base) root@work1:~/p4app-switchML/dev_root/build/bin# ./allreduce_benchmark
Signal handler thread started. Waiting for any signals.
Submitting 5 warmup jobs.
Warmup finished.
Submitting 10 jobs.
Job(s) #0# finished. Duration: #2066812641# ns Goodput: #4.15613# Gbps.
Job(s) #1# finished. Duration: #2125384548# ns Goodput: #4.04159# Gbps.
Job(s) #2# finished. Duration: #2104909004# ns Goodput: #4.08091# Gbps.
Job(s) #3# finished. Duration: #2113666141# ns Goodput: #4.064# Gbps.
Job(s) #4# finished. Duration: #2106568551# ns Goodput: #4.07769# Gbps.
Job(s) #5# finished. Duration: #2098990614# ns Goodput: #4.09241# Gbps.
Job(s) #6# finished. Duration: #2058701300# ns Goodput: #4.1725# Gbps.
Job(s) #7# finished. Duration: #2752398271# ns Goodput: #3.12089# Gbps.
Job(s) #8# finished. Duration: #2040120838# ns Goodput: #4.2105# Gbps.
Job(s) #9# finished. Duration: #2046366958# ns Goodput: #4.19765# Gbps.
All jobs finished.


Min 2040120838 ns 4.2105 Gbps
Max 2752398271 ns 3.12089 Gbps
Median 2104909004 ns 4.08091 Gbps
Mean 2151391886 ns 3.99273 Gbps
Std dev 2.02332e+08 ns
Cleaning up.
Signal handler thread is exiting
```
however i can see 'Dropped' in controller  increase fastlly when run benchmark. it has small influence i guess。

```
SwitchML>show_statistics
             Broadcasted         Recirculated       Retransmitted          Dropped
  Index    Set 0     Set 1     Set 0     Set 1     Set 0     Set 1     Set 0     Set 1
    0      371383    371378      0         0         92        0       371390    371380
    1      371383    371378      0         0         92        0       371390    371380
    2      371383    371378      0         0         92        0       371390    371380
    3      371383    371378      0         0         92        0       371390    371380
    4      371383    371378      0         0         92        0       371390    371380
    5      371383    371378      0         0         92        0       371390    371380
    6      371383    371378      0         0         92        0       371390    371380
    7      371383    371378      0         0         92        0       371390    371380

```

 I guess controller is no problem , please check my log "[pytorch.txt](https://github.com/p4lang/p4app-switchML/files/9215662/pytorch.txt)" ,why it has fall into  "Worker thread '0' QP 10:0x632 reposting write ..."

“if (completions[i].opcode == IBV_WC_RECV_RDMA_WITH_IMM) {” in  rdma_worker_thread.cc is related to this questions probably

**Comment by lvleiai123** [comment]
hello ,i  debug it and find the problem , however， i don't know how to solve it  .
                `if (completions[i].opcode == IBV_WC_RECV_RDMA_WITH_IMM) {` in rdma_worker_thread.cc , this Judgment conditions can not run success  and 'IBV_WC_RECV_RDMA_WITH_IMM' related to rdma driver , am i make rdma in a  wrong way ?

**Comment by OasisArtisan** [comment]
Although your throughput does not look too bad for 1 core with DEBUG mode enabled, the drop count seems off.
Have you disabled ICRC checking on the client side? 
If not follow the instructions in the [scripts](https://github.com/p4lang/p4app-switchML/tree/main/dev_root/scripts) directory.

By the way you still did not tell me what integration method you used for pytorch. Pytorch plugin? Pytorch Patch?

**Comment by lvleiai123** [comment]
Sorry for that: i‘m  using Pytorch Patch。And i have disabled ICRC correctly , however it keep “Retransmitted ” status 。
Finally，I alter the patch file in line 144 ,149  which from  "AllReduce" to “AllReduceAsync”  and recomplied it , it has worked successfully, i can run my pytorch  with command` “python main.py -a resnet50  --dist-url 'tcp://2.2.2.1:10000' --dist-backend 'gloo'  --gpu 0   --world-size 2 --rank 0 -j 8  /imagenet/tiny-imagenet-200/”`  now  。

So，i have a quetion ,
the only difference is "    job->WaitToComplete();"  in `“AllReduce”` and  `"AllReduceAsync"` in `context.cc`, if can i delete it ?

**Comment by 1908639561** [comment]
Hi, @lvleiai123 , I changed the "AllReduce" to "AllReduceAsync " the way you did, but I still fail and the switch keeps retransmitting and dropping packets.

**Comment by lvleiai123** [comment]
i set `batch_size=16`  in main.py  which is my own program ,i can get a good speedup now。
