### ISSUE TITLE
No module named 'switchml_pb2'

### ISSUE THREAD

**Issue by VoidStardust** [p4lang/p4app-switchML#2]
Hello,
I try to run SwitchML as a benchmark, but encountered a problem when trying to run the python controller as below:

``` shell
root@localhost:~/Projects/git/p4app-switchML/dev_root/controller# python switchml.py 
Traceback (most recent call last):
  File "switchml.py", line 45, in <module>
    from grpc_server import GRPCServer
  File "/root/Projects/git/p4app-switchML/dev_root/controller/grpc_server.py", line 20, in <module>
    import switchml_pb2
ModuleNotFoundError: No module named 'switchml_pb2'
```

Environment:
* SDE version: 9.3.0
* Python version: 3.8.11

Looking forward to your reply.

**Comment by OasisArtisan** [comment]
Hey, thanks for reaching out.

You should use the makefile inside the controller directory to generate these modules from protobuf.

Simply run

    make

when you are inside the controller directory and try again.

Let me know if that fixed your issue.

Cheers.

**Comment by VoidStardust** [comment]
That works for me, thanks for your reply.

I just modified the *GRPC_HOME* path to my own installation of grpc, for I don't need to run `make third_party` to build embedded grpc.

``` Makefile
# dev_root/protos/Makefile
GRPC_HOME ?= <path-to-grpc>
```

Besides, I need to fix some dependency problem.

``` bash
python3.8 -m pip install -U grpcio # upgrade to 1.38.1, older version (1.17.0) may not work
python3.8 -m pip install ansicolors
```

**Comment by OasisArtisan** [comment]
We haven't tested with other GRPC versions but hopefully everything works out.

Good luck.
