### ISSUE TITLE
Failed to install the Pytorch Patch

### ISSUE THREAD

**Issue by 1908639561** [p4lang/p4app-switchML#20]
When I run "git apply /home/antl/wjk/p4app-switchML/dev_root/build/" in the "/home/antl/wjk/p4app-switchML/dev_root/build/ switchml_pytorch.patch" from https://github.com/p4lang/p4app-switchML/tree/main/dev_root/frameworks_integration/pytorch_patch#3-apply-the-switchml-pytorch-patch-to-pytorch, it has the following problem.

![image](https://user-images.githubusercontent.com/95405577/182360348-a8b92c84-1b45-45bb-b4f6-dfe85037eacd.png)

But I see in the "rdma_pytorch.dockerfile"  https://github.com/p4lang/p4app-switchML/blob/b5c74a04fa66faa82acab154a4e21c8f76d913f2/dev_root/dockerfiles/rdma_pytorch.dockerfile#L92 that it runs this command in the "p4app-switchML/dev_root" directory, so I follow this and I don't get any output, I feel it should work. But when I finished compiling pytorch, "import torch_switchml" did not find sml, which means that I failed to install the patch. 
![image](https://user-images.githubusercontent.com/95405577/182360713-3bd26daf-3580-4727-808e-15bedb39003b.png)
I don't know what the reason is.

My conda environment is installed with：
[environment.txt](https://github.com/p4lang/p4app-switchML/files/9241662/environment.txt)

**Comment by OasisArtisan** [comment]
The patch must work if you are checking out to the correct PyTorch version

    git checkout 57bffc3 # The 1.7.1 version
    git submodule sync
    git submodule update --init --recursive

As for importing torch_switchml. You only do that for the pytorch plugin integration. The pytorch patch integrates into the existing Gloo backend. You only need to use gloo as your backend and SwitchML will kick in for allreduce when it supports the operation (sum for float32 and int32).

**Comment by 1908639561** [comment]
I think I have it installed and I can run "allreduce_pytorch_benchmark.py" successfully. But when I try to train the model, I find that the switch keeps dropping packets and retransmissions. I have tested adjusting "timeout", "timeout_threshold" or "timeout_threshold_increment ", but it still does not work. Do you have any suggestions?
![image](https://user-images.githubusercontent.com/95405577/182987903-7fbb7ef7-c66e-4907-bd08-c60c35121582.png)

My training file：
[main2.py.txt](https://github.com/p4lang/p4app-switchML/files/9264728/main2.py.txt)
[vgg.py.txt](https://github.com/p4lang/p4app-switchML/files/9264746/vgg.py.txt)

My configuration file：
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/9264729/switchml.cfg.txt)

**Comment by lvleiai123** [comment]
my quetion is same to you . 
DPDK is OK。RDMA is retransmissions。
MARK.

**Comment by 1908639561** [comment]
When I use only the cpu, it seems to work fine. But I can't view any of the packets on the switch side. I am using "Pytorch Patch" and I have disabled ICRC checking on the client side.
![image](https://user-images.githubusercontent.com/95405577/183325907-31fb4596-7388-4535-be1a-32e8dde176e7.png)
![image](https://user-images.githubusercontent.com/95405577/183325930-bfacd395-cdfa-43bf-9d24-1e9cce9f14b8.png)
