### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by lvleiai123** [p4lang/p4app-switchML#22]
hi，i'm using DPDK. 
I have  got  3517s  when i run pytorch without switchml and 1912s  with p4app-switchml ，it speedup to 46%。
However ,when i adjust `batch_size=16`  to  `batch_size=256`  in ‘main.py’ which is my AI program，i just got 924s without switchml and 916s with p4app-switchml , it just speedup  0.8%。why `batch_size` become so importance？ i do not know  if  my  'Tesla V100-PCIE' card reach bottleneck.   how about your `batch_size` .
![image](https://user-images.githubusercontent.com/59639597/185029245-01318766-dd7d-4bbd-8765-53b671301504.png)

**Comment by OasisArtisan** [comment]
Hello, nice looking graph you got there. 

SwitchML accelerates the communication step of distributed deep learning. Therefore you will only observe significant speedups when communication is the bottleneck. This might not always be the case depending on the model you are using and the setup you have (Computer power, network bandwidth...etc.).

Now coming to your question about batch size, the larger the batch size, the less communication you perform relative to computation. So when you increase the batch size, you shift the bottleneck to computation more than communication. Sometimes even doing this is not enough to remove the communication bottleneck so SwitchML can be still very useful, in other cases, like your model here, it seems the communication bottleneck can be alleviated by simply increasing the batch size.

Of course increasing the batch size to be very big is not always a good idea statistically as you would be working with stale parameters for a longer time so you might want to have some time to accuracy results here as well.

Hope that clears up the confusion.
