### ISSUE TITLE
segment

### ISSUE THREAD

**Issue by LaceFern** [p4lang/p4app-switchML#26]
Hello. I recently try to run allreduce_benchmark with GPU. However, when I run it, the console prints "Segmentation fault (core dumped)" after it printed "Submitting 5 warmup jobs.". I find that when I compile the allreduce_benchmark using the command "make allreduce_benchmark  DPDK=1 MLX5=1 VCL=0 CUDA=1" under the /p4app-switchML/dev_root/benchmarks/, the console prints that "Makefile:72: CUDA is set. But GPU memory is not yet handled by any of the prepostprocessors in the client library." I think this problem causes segment fault but don't understand why it happens. Would you like to give some advice? Thanks in advance!

**Comment by OasisArtisan** [comment]
Hey Lace, 
Yeah the CUDA flag is not yet fully supported. The benchmark is going to send GPU pointers to the client library, but the client library prepostprocessors will deal with it as a CPU pointer hence the segmentation fault. This means that you have to copy your tensors to CPU before you use SwitchML.

**Comment by LaceFern** [comment]
Thanks very much!

**Comment by lq470379** [comment]
Does this mean the performance reported in switchML paper is with back and forth tensor copy between CPU and GPU memory?

**Comment by AmedeoSapio** [comment]
Yes, that is correct. The training experiments reported in the NSDI'21 paper are copying data from the GPU buffer to the CPU memory, performing quantization and then using DPDK to send data to the switch. The same with inverted order and dequantization happens in the other direction.  
We expect a significant improvement with 1) quantization done by the GPU and 2) using GPU-direct RDMA or similar technologies to skip the data copies to/from CPU memory, but unfortunately we haven't implemented this yet.
