### ISSUE TITLE
DPDK flow isolated mode failed 

### ISSUE THREAD

**Issue by kfertakis** [p4lang/p4app-switchML#30]
Hi,

I'm trying to run an experiment with workers having a mix of MLX5 NICs and some workers have Intel 82599 ES 10G NICs. However, when the `allreduce_benchmark` is started in the worker with the intel NIC, an error is generated from DPDK saying `Flow isolated mode failed: 1 Function not implemented`. Any insights on this would be much appreciated.

Thanks.

**Comment by Shangwei-Li** [comment]
Intel i40e driver have not implemented isolated mode, which guarantees that all ingress traffic comes from defined flow rules only. But it should be fine if all incoming packets are SwitchML packets since flow directors will handle them well.

**Comment by AmedeoSapio** [comment]
Hi, 
yes, I agree with @Shangwei-Li. The Intel i40e driver does not support the isolated mode, but it is not a problem if you only have SwitchML traffic in that interface. See [here](https://doc.dpdk.org/guides/prog_guide/rte_flow.html#flow-isolated-mode) for the isolated mode description.  
You can comment out this line to avoid enabling the isolated mode.
https://github.com/p4lang/p4app-switchML/blob/1fc7e676919a51c6f67bcf823b72e1d52769c6a4/dev_root/client_lib/src/backends/dpdk/dpdk_master_thread_utils.inc#L277

**Comment by kfertakis** [comment]
I see. Thank you both for the comments. I managed to get it working.
