### ISSUE TITLE
Confusion about the intergration of pytorch.

### ISSUE THREAD

**Issue by carlzhang4** [p4lang/p4app-switchML#4]
Hi there,
I read your PyTorch patch, and was confused about the modification, your modification was based on Gloo backend code, which would synchronize the stream every time the procedure call the AllReduce function. Isn't it inefficient? It seems that NCCL backend would put all the AllReduce operations into an async work queue which does not require synchronizing the stream before every AllReduce call.
Best regards

**Comment by OasisArtisan** [comment]
That is a very good observation. 

Currently, SwitchML does not deal with GPU buffers directly and requires that they be copied to host memory similar to how GLOO operates. That is why we use the same logic as GLOO where we let PyTorch copy to host side memory, perform a synchronous allreduce, then copy memory back.

You are correct in that we can increase the efficiency by letting SwitchML handle the copies and letting PyTorch use the asynchronous all reduce operation. We are already working on a SwitchML PPP and a new PyTorch Patch that does exactly what you are describing. We're still testing and ironing out some kinks but hopefully we can push it soon.

**Comment by carlzhang4** [comment]
Thank you for replying. Anyway, this work is brilliant.

**Comment by OasisArtisan** [comment]
Thanks. Feel free to reach out if you have any other problems.
