### ISSUE TITLE
Could not start the context due to missing configuration.

### ISSUE THREAD

**Issue by LaceFern** [p4lang/p4app-switchML#6]
Hello. I ran **make RDMA=1** under **p4app-switchML/dev_root/client_lib/**, then ran **make RDMA=1**  under **p4app-switchML/dev_root/examples/**, finally ran **./hello_world** under **p4app-switchML/dev_root/build/bin/**. I found Line 32: ctx.Start() in  p4app-switchML/dev_root/examples/hello_world/main.cc could not run correctly and the process aborted as the following fig. shows.
<img width="594" alt="1646639449(1)" src="https://user-images.githubusercontent.com/32428729/156989749-8c13ffbe-188e-4b25-844e-3c5b65d12a6d.png">
So how to run the hello_world example correctly? Thanks in advance for any help!

**Comment by LaceFern** [comment]
Thanks, your reply helps a lot. However now I meet another problem. I ran the hello_world example in a server without any p4 switch working, with an aim to check if rdma packets could be generated correctly. However, I found the tx pkt count in the 100Gb/s NIC of this server didn't increase. I wonder if these are some configurations that need to be updated with a certain NIC like name, ip, mac, etc?

**Comment by mcanini** [comment]
The NIC counters reported by the kernel (via ifconfig) might not reflect the RDMA packets. You can use Mellanox tools to read the NIC counters directly.

**Comment by LaceFern** [comment]
But, even when I link the server's 100Gb/s NIC port to one port of p4 switch, there was no packet cached by the switch as well. I want to use switch to catch some packets like packets for building rdma communication. So I wonder if there are any configuration I haven't set correctly. 

1. I find that in the switchml.cfg the controller ip is 127.0.0.1, which seems related packets won't send out to the p4 switch but loop back to the localhost. Should I change it to the ip of the control plane of the p4 switch? 

2. What's the difference between the controller ip and the switch_ip? Is the controller ip used to build rdma communication? Where is the switch_ip and should I change it? 
<img width="487" alt="1646828768(1)" src="https://user-images.githubusercontent.com/32428729/157441597-f49d119f-cb9a-4ac6-a7d8-f7b02b9b5b21.png">

3. For hello_world example, how is the server linked with p4 switch by cable when num_workers = 1? Should I link the NIC port to a specific port of p4 switch instead of random choice?

**Comment by OasisArtisan** [comment]
**SwitchML needs 3 components to function.**
1. **Client library** which you seem to have been able to compile and run.
2. **Controller.** Which is a python program that acts like a mediator between the switch and the clients and you have to run this separately on a machine.
3. **P4** program which has to be uploaded to your switch so that it performs the switchml aggregation logic.

Without these 3 components you cannot run SwitchML with RDMA. You can test and run with the DUMMY backend. I also suspect that you did not change the backend from DUMMY to RDMA in the configuration which is something that you need to do to test RDMA.

Okay now assuming you have the p4 code uploaded correctly and the python controller running on a machine, with proper configuration you can run the hello_world example.

**Coming to your question about switch_ip and controller_ip:**

You give the client the controller_ip so that it knows how to reach the controller program. If the controller was running on the client host then you can set this to loopback 127.0.0.1.

The switch_ip is what you give as an argument to the controller so that it knows how to reach the switch. If the controller was running on the switch itself then you can set this to loopback 127.0.0.1.

**As for your third question**
@AmedeoSapio can correct me on this but I believe you can connect it to any port on the switch as long as it is part of the first pipeline which is not set to be in loopback mode.

Hope that this clears up any confusion.

**Comment by AmedeoSapio** [comment]
Yes, I confirm that what @OasisArtisan said is correct. With the current version, you can use any port on pipe 0 of the switch to connect the server, which are all ports with data plane number (`D_P` value in `pm show`) less than or equal to 64. 
We will soon remove this limitation and allow to use any port on the switch. 

You need to run the controller to see any packet reaching the switch for 2 reasons: 1) the controller enables the ports on the switch (you need to pass a yaml file to the controller like [this one](https://github.com/p4lang/p4app-switchML/blob/main/dev_root/controller/ports.yaml) to specify what ports to enable on how); and 2) the end host library needs to communicate with the controller to establish a session before it can start sending packets.

**Comment by VoidStardust** [comment]
Hello,
I'm working on SwitchML benchmark with @LaceFern now.
We currently own a 32 front-port tofino switch, so I modified the controller code `switchml.py` as below

``` python
            # Enable loopback on front panel ports
            loopback_ports = (
                [64] +  # Pipe 0 CPU ethernet port
                # Pipe 0: all 16 front-panel ports
                #list(range(  0,  0+64,4)) +
                # Pipe 1: all 16 front-panel ports
128     -       list(range(128, 128 + 64, 4)) +
    128 +       list(range(128, 128 + 64, 4)) #+
                # Pipe 2: all 16 front-panel ports
130     -       list(range(256, 256 + 64, 4)) +
    130 +       # list(range(256, 256 + 64, 4)) +
                # Pipe 3: all 16 front-panel ports
132     -       list(range(384, 384 + 64, 4)))
    132 +       # list(range(384, 384 + 64, 4))
    133 +   )
```

I find that you have not support 512B packet yet, so I guess we can only run with 256B packet. I wonder if there are any other configuration we should modify to make SwitchML work with our 32 port switch. For example,  I noticed that you set port 192 into loopback mode, but port 192 for our switch is the cpu port. So we may need this port to allow the data plane to forward the control packet to the controller running on the switch. I'm not sure whether to remove it or change it to another port (port 68, I suppose).

**Comment by AmedeoSapio** [comment]
Hi, 
yes, you are right, we only support 256B payloads on 2-pipes switches, and additionally 1024B in 4 pipes switches. 
Consider that there are 2 kinds of 32 front-ports tofino switches: in one the tofino chip has 2 pipes, in the other Tofino still has 4 pipes and ports in 2 pipes are internally set in loopback mode. 

With 4 pipes switches (regardless of how many front panel ports) we can use the folded pipeline approach and support 1024B payloads. 

Please pull the last commit I pushed. Now the controller does not enable the folded pipeline by default. This allows to use 2-pipes switches. If you have a 4 pipes switch and want to enable the folded pipeline, you can use the enable-folded-pipe argument when starting the controller. 
Let me know if this solves your issue.

**Comment by VoidStardust** [comment]
Hello,

We have meet exactly the same problem as #8 with the allreduce benchmark.

According to the advise you gave in https://github.com/p4lang/p4app-switchML/issues/8#issuecomment-1067503416, our config file is as below:
[switchml.cfg.txt](https://github.com/p4lang/p4app-switchML/files/8250320/switchml.cfg.txt)

We are also stuck at `ctx.WaitForAllJobs();`, and the message from the controller is

```
SwitchML>show_ports

  Port Up Valid Enabled Speed  FEC    Tx Packets        Tx Bytes        Rx Packets        Rx Bytes        Rx Errors        Tx Errors        FCS Errors   
  17/0 1    1      1    100G  REED_SOLOMON        0                0                2               228               0                0                0        


SwitchML>show_ports

  Port Up Valid Enabled Speed  FEC    Tx Packets        Tx Bytes        Rx Packets        Rx Bytes        Rx Errors        Tx Errors        FCS Errors   
  17/0 1    1      1    100G  REED_SOLOMON        5               1416              7               1644              0                0                0        


SwitchML>show_rdma_workers

                                                   Received              Sent        
 Worker ID     Worker MAC        Worker IP     Packets  /    Bytes      Packets  /    Bytes    
     0      98:03:9b:ca:40:18    10.0.0.7         0     /      0           4     /    1240     


SwitchML>show_statistics

             Broadcasted         Recirculated       Retransmitted          Dropped       
  Index    Set 0     Set 1     Set 0     Set 1     Set 0     Set 1     Set 0     Set 1   
    0        1         0         0         0         0         0         0         0     
    1        1         0         0         0         0         0         0         0     
    2        1         0         0         0         0         0         0         0     
    3        1         0         0         0         0         0         0         0     
    4        0         0         0         0         0         0         0         0     
    5        0         0         0         0         0         0         0         0     
    6        0         0         0         0         0         0         0         0     
    7        0         0         0         0         0         0         0         0     


```

So it seems that the client does not receive the data from switch, or the format of broadcasted packets are not recognized by the clients.

I noticed that in your last commit https://github.com/p4lang/p4app-switchML/commit/7ded628eb31a86e80ad0bf65e72a3e94e0e13d05 you remove all the loopback ports for the unfolded pipeline to support 32 ports switch, but I thought we need at least one port for resubmit in the harvast phase, cuz p4 can only read 32 elements in one packet.

**Comment by AmedeoSapio** [comment]
Yes, it is true that we need to recirculate once during harvest to get the second batch of 32 elements.  You can see [here](https://github.com/p4lang/p4app-switchML/blob/7ded628eb31a86e80ad0bf65e72a3e94e0e13d05/dev_root/controller/next_step_selector.py#L77) that the last packet (`Flag.LAST`), in the case with only 64 elements per packet (256B = `PacketSize.MTU_256`) , is recirculated for the harvest phase (`recirculate_for_HARVEST7`) only once using port 68 (`port[7]`). Port 68 is an internal port already in loopback mode, so there is no need to set it explicitly. 

Anyway, `Broadcasted` and `Sent packets` in the statistics say that packets are sent out, so my guess is that there is a problem with the NIC dropping those packets when receiving them. What NIC do you have? If it is a Mellanox NIC, can you show me the output of `disable-icrc.sh`? (Note that if you are not using the `mlx5_0` device, you need to change this line in that script `DEV=mlx5_0`). 
Can you also check the NIC counters as mentioned in [the comment](https://github.com/p4lang/p4app-switchML/issues/8#issuecomment-1067503416) to see if and why packets are dropped by the NIC?

**Comment by LaceFern** [comment]
The output of disable-icrc.sh is shown as below.
<img width="748" alt="1647338199(1)" src="https://user-images.githubusercontent.com/32428729/158352899-1c9d820e-4969-423e-b40e-51af15df5147.png">

I ran the script in [the comment](https://github.com/p4lang/p4app-switchML/issues/8#issuecomment-1067503416) before and after the experiment. The differences between two outputs are shown as below.
![image](https://user-images.githubusercontent.com/32428729/158353422-3a1d9f9b-6ac5-48e7-835b-156fd0c653bc.png)

I guess packets sent from the switch to the worker are in wrong format so the worker cannot recognize it.

**Comment by AmedeoSapio** [comment]
Hi,
Are you using the config file that @VoidStardust sent in the previous commit? 
Are you using `packet_numel = 64` in your config file? 
With a 2 pipes switch, 64 elements per packet is the only supported value. 
The cfg file you shared earlier used mlx5_1, but the picture that you shared is disabling ICRC in mlx5_0. 
Please check that ICRC is disabled in the right interface and try again.

**Comment by LaceFern** [comment]
Thanks! We've run examples successfully!
